name: Build Next.js web application
on: push
jobs:
  build-projects:
    name: Build projects
    run-on: ubuntu-latest
    steps:
     name: Upload static site content
     uses : actions/upload-pages-artifact@v3
     with:
       path: ./out
       name: github-pages
       retention-days: 1
